# Generated by Django 2.0.1 on 2018-03-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decorationimg',
            old_name='is_active',
            new_name='is_new',
        ),
    ]
